import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Simple role check for admin/staff (client-side only for now)
  let isAdmin = false;
  if (typeof window !== "undefined") {
    const user = localStorage.getItem("user");
    if (user) {
      const parsed = JSON.parse(user);
      isAdmin = parsed.role === "admin" || parsed.role === "staff";
    }
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Optionally show admin nav here if isAdmin */}
        {children}
      </body>
    </html>
  );
}
